const fs=require('node:fs');
const assert=require('node:assert/strict');
const html=fs.readFileSync('index.html','utf8');
assert.match(html,/<input type="email" id="email" required/);
assert.match(html,/<button type="button" id="run">/);
assert.match(html,/email\.checkValidity\(\)/);
assert.match(html,/Verification required/);
assert.match(html,/Nothing has been submitted or sent/);
assert.match(html,/status\.hidden=true/);
assert.doesNotMatch(html,/src="progress\.js"|src="guided\.js"/);
assert.doesNotMatch(html,/window\.open\(|fetch\(|XMLHttpRequest|<form[^>]*action=/i);
console.log('PASS: single-field interface, email validation, explicit verification gate and no unauthorised submissions.');
